%%
clear
close

% minimal preprocessing of raw EEG/ECG data from both sites
% WIM_HB_preproc_PBI -- download output files generated by this script from https://osf.io/v9xsw/
run WIM_HB_preproc_MBI -- download input files to run this script from https://osf.io/ey3ca/

% EEG-ECG artefact rejection
run WIM_HB_preproc_CLN
run WIM_HB_preproc_ASR
run WIM_HB_preproc_ECG
run WIM_HB_preproc_ICA
run WIM_HB_preproc_ICA_rej
run WIM_HB_preproc_CFA
run WIM_HB_preproc_BHI

% EYE preprocessing
run WIM_HB_preproc_EYE % download output files generated by this script for Paris data from https://osf.io/v9xsw/
